
[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "none"

opacity = 0.7
# blur = true


[font]

normal.family = "FiraCode Nerd Font"
size = 16


[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
]

[general]
import = [
# "~/.config/alacritty/themes/themes/coolnight.toml"
"~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
# "~/.config/alacritty/themes/themes/catppuccin.toml"
# "~/.config/alacritty/themes/themes/dracula.toml"
# "~/.config/alacritty/themes/themes/github_dark.toml"
# "~/.config/alacritty/themes/themes/inferno.toml"
# "~/.config/alacritty/themes/themes/iris.toml"
# "~/.config/alacritty/themes/themes/Mariana.toml"
# "~/.config/alacritty/themes/themes/monokai_charcoal.toml"
# "~/.config/alacritty/themes/themes/monokai_pro.toml"
# "~/.config/alacritty/themes/themes/monokai.toml"
# "~/.config/alacritty/themes/themes/moonlight_ii_vscode.toml"
# "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
#
]


