
[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "none"

opacity = 0.7
blur = true


[font]

normal.family = "FiraCode Nerd Font"
size = 16


[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
]

[general]
import = [
"~/.config/alacritty/themes/themes/coolnight.toml"
]


